### ISSUE TITLE
Fisher vector computation

### ISSUE THREAD

**Issue by wlin-at** [alexanderrichard/squirrel#2]
Hi, is it also possible to release the code for Fisher vector computation?
"The Fisher vector representation for each frame is computed over a sliding window of 20 frames" - Does it mean that each frame corresponds to one sliding window of 20 frames (with this frame in the middle of the window?), and all the 15-frame-dense-trajectories which are completely included in this sliding window are used to compute one 8192-d (2x64x64) Fisher vector for this frame? Thanks in advance.
Regards

**Comment by alexanderrichard** [comment]
Hi,

each 15-frame dense trajectory ending in a frame that lies within the 20 frames window is used in the computation.
I don't have the code for this anymore, sorry.

Best,
Alex
