### ISSUE TITLE
Files are not available for download

### ISSUE THREAD

**Issue by MiaQiu** [alexanderrichard/squirrel#3]
Page: https://github.com/alexanderrichard/squirrel/tree/master/examples/cvpr2017
The URL to download the data and trained model are both not accessible anymore.
1) download the data:
    **wget -O data.zip https://uni-bonn.sciebo.de/index.php/s/yt0MHmQJNzQalJR/download**
    unzip data.zip
    rm data.zip
2) train the model:
    ./train.sh
   OR download our trained model for Breakfast here:
   **https://uni-bonn.sciebo.de/index.php/s/lFTlv5obv8JZkc5/download**

**Comment by alexanderrichard** [comment]
I'm sorry that the features are not online anymore. I graduated and no longer have access to the university servers, unfortunately I will not be able to fix this :(
