### ISSUE TITLE
An request for the data download links

### ISSUE THREAD

**Issue by hhhh1138** [alexanderrichard/squirrel#4]
Excuse me, recently our group is working on weakly supervised segmentation task, and we want to use the HTK methods to be one of the baselines. But the data in /master/examples)/cvpr2017/ can not be downloaded through the urls. Could you update your links in your free time? That's very much appreciated.

**Comment by alexanderrichard** [comment]
see this issue: https://github.com/alexanderrichard/squirrel/issues/3
